services:
  - type: web
    name: splashpass
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_PASSWORD
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: splashpass-db
          property: connectionString

databases:
  - name: splashpass-db
    plan: free
